### ISSUE TITLE
Exact Path for saving rules.xml file

### ISSUE THREAD

**Issue by SaiBandaru1001** [mwittrock/cpilint#10]
Exact Path for saving rules.xml file?

**Comment by mwittrock** [comment]
Hi. You can save the rules file anywhere you want. You run CPILint from the command line. If you run it from the same directory that holds the rules file, the -rules option just needs the name of of the file. Otherwise, pass it the path to the rules file.

**Comment by SaiBandaru1001** [comment]
Hi,

Thanks for your reply.

I have saved the rules file in the same location where I installed the
cpilint, but still when I'm trying to run the query I get the below one.

The provided rules file does not exist.

Below is the query that I'm using.
cpilint -rules disallow-log4j.xml -tmn-host <host> -username <user>

and tried with the path as well, still getting the same error.

Could you please do the needful.

Many thanks,
SaiBandaru.

**Comment by mwittrock** [comment]
Hi

The rules file doesn't have to be in the same directory you installed CPILint (in fact it probably shouldn't be). What matters is the directory you run the command from. 

In your case, if you do "dir disallow-log4j.xml" from the command line and it doesn't find the file, your command won't work. Either run it from the same directory that holds the disallow-log4j.xml file or give an absolute or relative path to it. So instead something like -rules \some\path\disallow-log4j.xml (if you are on Windows, use forward slashes if you are not).

This is a command line usage/file system thing, not a CPILint issue.

Regards,

Morten
