### ISSUE TITLE
Feature: Groovy best practices checks

### ISSUE THREAD

**Issue by fippu82** [mwittrock/cpilint#11]
I would like to make a feature suggestion: Add a check for Groovy coding best practices. First rule could be to ensure that variables are always defined with at either "def" or explicit type. I got the idea from this blog: https://blogs.sap.com/2017/06/22/avoid-binding-variables-in-groovy-scripts/

**Comment by atz-adobson** [comment]
@fippu82 Take a look at groovy linting instead
https://github.com/nvuillam/npm-groovy-lint

**Comment by mwittrock** [comment]
Added to feature requests - thank you!
