### ISSUE TITLE
Cannot read the array length because "buf" is null

### ISSUE THREAD

**Issue by svenkelemen** [mwittrock/cpilint#14]
Hi, I'm using a different java version (java version "17.0.2" 2022-01-18 LTS) and getting the error below, for some simpler exports it works. Debug log stops at  "Starting inspection of iflow artifacts". SAP Integration Suite Version - 3.60.1
Please help :-) 

![image](https://github.com/mwittrock/cpilint/assets/37483494/5e178156-063d-438b-9037-2f7e89fdbfb7)

**Comment by mwittrock** [comment]
Hi! Could you possibly email me the log file? My email address is my GitHub username AT gmail dot com.

Regards,

Morten

**Comment by svenkelemen** [comment]
The issue happened because I used ZIP created by exporting the whole Package with multiple Artifacts (iFlows) by:
Integration Suite -> Integrations and APIs / "your package" -> Export 

Instead, I should be using ZIP with just one iflow, downloaded by the following steps: 
Integration Suite -> Integrations and APIs / "your package" -> (Tab "Artifacts") -> (under "Actoions") -> Download 

<img width="387" alt="image" src="https://github.com/mwittrock/cpilint/assets/37483494/18ae59a5-c221-47f8-999c-133e35a6f816">

I guess I should check directly in the tenant, where we get quite a few options for controlling what to check. 
* Thanks Morten
