### ISSUE TITLE
Installation error - The system cannot find the path specified.

### ISSUE THREAD

**Issue by RaghuramJ04** [mwittrock/cpilint#17]
Hi Team,

I have installed and followed the guidelines given, however I get below error while executing cpilint cmd.

Please let me know if I am missing any point. or any step to resolve this issue. Thank you in advance.
---------------------------------
C:\Users\raghu\OneDrive\Documents\cpilint-1.0.5\cpilint-1.0.5\bin>cpilint -version
The system cannot find the path specified.
--------------------------------

Regards,
Raghuram.J

**Comment by mwittrock** [comment]
Hi there

It would seem you have not added the CPILint bin directory to your PATH, and the current directory is not in your PATH either.

Please follow the [installation instructions in the wiki](https://github.com/mwittrock/cpilint/wiki/Installing-and-running-CPILint).

Generally, you shouldn't run CPILint directly from the installation folder, and when bin is in your PATH, you won't have to.

Regards,

Morten

**Comment by mwittrock** [comment]
P.S. Any changes you make to your environment variables are not visible to an open Windows Terminal/Command Prompt. So you need to exit it and relaunch for the changes to take effect.

**Comment by 51054554** [comment]
Hi,
I'm getting the same error here.
I already tried the previous version (1.0.4), restarted the computer several times but nothing had any effect.

![image](https://github.com/user-attachments/assets/8da7f490-1c62-4819-a5a9-90c8cb26f87a)
![image](https://github.com/user-attachments/assets/42a3f989-6172-4d2c-b6d9-18dbe22247c1)

**Comment by mwittrock** [comment]
Hi

Please show me the output of these two commands:

`set JAVA_HOME`
`java -version`

Regards,

Morten

**Comment by RaghuramJ04** [comment]
Hi,

Thank you for the reply.

PATH variable is set to bin directory as given in the installation guide. I have deleted all and added again just to re-check. Still I am getting the same error.

Please find the details below.
![CPILINT_java_home](https://github.com/user-attachments/assets/84562377-72eb-4b2a-aa0b-4d1d70011017)
![CPILINT_Path](https://github.com/user-attachments/assets/e3249741-f82b-4d28-8699-305689d80a53)
![CMD_CPILINT](https://github.com/user-attachments/assets/3ba4e2fc-be53-4d45-8395-b4825d994e02)



Regards,
Raghuram.J

**Comment by mwittrock** [comment]
Now try this please:

`%JAVA_HOME%\bin\java -version`

Regards,

Morten

**Comment by 51054554** [comment]
Hi Morten,

Thank you very much for the help.
My case was resolved, the problem was in the CPILINT_JAVA_HOME variable.

Best regards,

**Comment by mwittrock** [comment]
Hello again

Glad to hear it. Have fun with CPILint!

Regards,

Morten

**Comment by RaghuramJ04** [comment]
Hi Morten,

Looks like you have closed the issue. Joao posted his issue in my case.
Could you please reopen or let me know if i can raise a new case ?

As suggested below is the response for %JAVA_HOME%\bin\java -version...

C:\Users\raghu>%JAVA_HOME%\bin\java -version
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

Regards,
RAghuram.J

**Comment by mwittrock** [comment]
Hi

Ah, sorry about that - I hadn't paid attention to the user names.

This is very likely not a CPILint issue, but rather related to either the Windows environment or the Java installation. Please try these two commands:

`"%JAVA_HOME%"\bin\java -version
"%CPILINT_JAVA_HOME%"\bin\java -version`

Note the quotation marks.

Regards,

Morten

**Comment by RaghuramJ04** [comment]
Thank you for the reply.

Please find the output of the given commands below..
C:\Users\raghu>"%JAVA_HOME%"\bin\java -version
java version "11.0.24" 2024-07-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.24+7-LTS-271)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.24+7-LTS-271, mixed mode)

C:\Users\raghu>"%CPILINT_JAVA_HOME%"\bin\java -version
The system cannot find the path specified.

Regards,
Raghuram.J

**Comment by mwittrock** [comment]
Hello again

There's your issue: The CPILINT_JAVA_HOME variable does not point to a Java installation. And the launch script will use this variable to locate Java, if the variable is present.

Since your JAVA_HOME variable is correct, you can simply delete the CPILINT_JAVA_HOME environment variable in Windows and everything will work.

Regards,

Morten

**Comment by RaghuramJ04** [comment]
Perfect !!!

Thank you Morten, it is working now.

Thank you for your help. :)

**Comment by mwittrock** [comment]
Great - thanks for confirming. Have fun exploring CPILint!

Regards,

Morten
