### ISSUE TITLE
Question: Typical development process/setup

### ISSUE THREAD

**Issue by larshp** [mwittrock/cpilint#3]
Wondering, what would the typical development process/setup be when using cpilint?

setup a scheduled job to run cpilint?

**Comment by mwittrock** [comment]
For now, interactive use is probably the main use case. However, it is definitely possible to schedule the tool to run in the background. Exit codes indicate whether issues were encountered, so you can also hook it into Jenkins or similar pipelines.

**Comment by peakMeissner** [comment]
Hello Morten Wittrock ,

I would like to start using cpilint in our SAP CPI landscape. I want to use cpilint in combination with jenkins. I was wondering if you have ever tried setting up this combination within a SAP Cloud Platform Neo enviroment? I’m aware that there are several blog posts regarding the deployment of jenkins to the SCP enviroment available. My question is how I can let jenkins access / use cplint? AFAIK there is not direct plugin available. Do you have any thought / help regarding this matter?

Best regards

Frederick

**Comment by mwittrock** [comment]
Hi Frederick

Copypaste from my reply on the SAP Community site:

"I haven’t done so myself, but the command line tool returns a status code which reflects whether there are issues or not, so you should be able to run the command in Jenkins and react on its outcome.

If you get this set up, it would be a great topic for a blog post :-D"

Regards,

Morten
